### ISSUE TITLE
got plantuml erro when include C4 on vscode

### ISSUE THREAD

**Issue by elderbig** [plantuml-stdlib/C4-PlantUML#190]
```plantuml
@startuml
!RELATIVE_INCLUDE = ./
' uncomment the following line and comment the first to use locally
' !include C4.puml
a --> b

@enduml
```
 I pulled C4 from 
`https://github.com/plantuml-stdlib/C4-PlantUML`
and copy C4_*.puml into local folder, where is my vscode workspace,then I edit plantuml like up,so I got erro:
```
Exception in thread "main" java.util.NoSuchElementException
at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
at net.sourceforge.plantuml.tim.expression.ReversePolishInterpretor.(ReversePolishInterpretor.java:84)
at net.sourceforge.plantuml.tim.expression.TokenStack.getResult(TokenStack.java:250)
at net.sourceforge.plantuml.tim.Eater.eatExpression(Eater.java:95)
at net.sourceforge.plantuml.tim.EaterAffectation.analyze(EaterAffectation.java:66)
at net.sourceforge.plantuml.tim.iterator.CodeIteratorAffectation.executeAffectation(CodeIteratorAffectation.java:100)
at net.sourceforge.plantuml.tim.iterator.CodeIteratorAffectation.doAffectation(CodeIteratorAffectation.java:86)
at net.sourceforge.plantuml.tim.iterator.CodeIteratorAffectation.peek(CodeIteratorAffectation.java:74)
at net.sourceforge.plantuml.tim.TContext.executeLines(TContext.java:240)
at net.sourceforge.plantuml.tim.TimLoader.load(TimLoader.java:71)
at net.sourceforge.plantuml.BlockUml.(BlockUml.java:128)
at net.sourceforge.plantuml.BlockUmlBuilder.init(BlockUmlBuilder.java:127)
at net.sourceforge.plantuml.BlockUmlBuilder.(BlockUmlBuilder.java:78)
at net.sourceforge.plantuml.SourceStringReader.(SourceStringReader.java:95)
at net.sourceforge.plantuml.SourceStringReader.(SourceStringReader.java:87)
at net.sourceforge.plantuml.SourceStringReader.(SourceStringReader.java:75)
at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:85)
at net.sourceforge.plantuml.Run.managePipe(Run.java:379)
at net.sourceforge.plantuml.Run.main(Run.java:180)
```
vscode version
```
version: 1.58.0
comiit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
date: 2021-07-12T23:51:36.303Z
Electron: 12.1.2
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux 
```
vscode plantuml plugin version = v2.14.0

**Comment by kirchsth** [comment]
Hi @elderbig,

C4.puml doesn't use 'RELATIVE_INCLUDE' at all (only the dependent C4_.....) therefore I think it should have no relevance and you can reproduce it with other (non C4_... related) *.puml files too.

You should set the variable in code via `%set_variable_value()` like below

```plantuml
%set_variable_value("RELATIVE_INCLUDE", ".")
```

I tried it locally on my machine with VS Code (v 1.60.1) and following code and this was working
(C4VersionDetails() is one of the last beta features which is not part of  the already deployed 2.3.0 version)

```plantuml
@startuml
%set_variable_value("RELATIVE_INCLUDE", ".")
!include C4_Component.puml

C4VersionDetails()

@enduml
``` 
![grafik](https://user-images.githubusercontent.com/21959385/135744625-336bbb73-8f01-4ad9-b889-ae1ddce5bb15.png)

BR Helmut

**Comment by kirchsth** [comment]
Hi @elderbig

maybe I found a better solution:

* you can set the PlantUML command line argumentes in VS Code via the settings
![grafik](https://user-images.githubusercontent.com/21959385/135745163-3b8b61d3-f500-4c4c-8f3d-69a26e2a9737.png)

**settings.json**
```
    "plantuml.commandArgs": [        
        "-DRELATIVE_INCLUDE=\".\""
    ]
```

* then not `set_variable_value()` call is required anymore
```plantuml
@startuml
' -DRELATIVE_INCLUDE="." is defined via settings
'  %set_variable_value("RELATIVE_INCLUDE", ".")
!include C4_Component.puml
C4VersionDetails()
@enduml
```

BR Helmut

**Comment by elderbig** [comment]
Thank U, I resolved this in another way,I download plantuml.jar ,and run plantuml.jar like this:
```
java -jar plantuml.jar -picoweb
```
then plantuml.jar listen port 8080 by default.then set plantuml-plugin in vscode, let plantuml-plugin request to local plantuml server(remote service https://plantuml.com/ can be use too) instead of plantuml-plugin its self,now C4 is a stdlib in plantuml and we can use it away.
