### ISSUE TITLE
Errors on Export to either HTML or PDF

### ISSUE THREAD

**Issue by EricGeigerQ** [plantuml-stdlib/C4-PlantUML#32]
When testing on a single diagram, I get errors when attempting to export to either HTML or PDF format.

When exporting to **HTML**, I get the following stack trace in the VS Code Output window:
```
Error found in diagram Basic Sample
java.lang.UnsupportedOperationException: HTML
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:400)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:238)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:179)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:127)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:71)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:425)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:202)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:111)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
Exception in thread "main" java.lang.UnsupportedOperationException: HTML
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:400)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:238)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:179)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:255)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:217)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:210)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:111)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
```

When exporting to **PDF**, I get this stack trace:
```
Error found in diagram Basic Sample
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:57)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:337)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:198)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:111)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:337)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:198)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:111)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
```

Exporting to an image (like **PNG**) seems to work as expected.

**Comment by Potherca** [comment]
This seems to be a know issue with the upstream vscode-plantuml project https://github.com/qjebbs/vscode-plantuml/issues/154

Closing as this can't be fixed in this repo.
